package ollama

import (
	"os"
	"path/filepath"
	"testing"
)

// /api/show has no path field, and its model_info omits keys the file carries:
// current hybrid artifacts come back with a null head_count_kv, which is the
// difference between sizing a cache and refusing to. The generated modelfile
// names the blob, so the file itself becomes readable again.
func TestBlobPathIsRecoveredFromTheModelfile(t *testing.T) {
	dir := t.TempDir()
	blob := filepath.Join(dir, "sha256-abc123")
	if err := os.WriteFile(blob, []byte("GGUF\x03\x00\x00\x00"), 0o600); err != nil {
		t.Fatal(err)
	}
	modelfile := "# Modelfile generated by \"ollama show\"\n" +
		"# To build a new Modelfile based on this, replace FROM with:\n" +
		"# FROM qwen3.6:27b\n\nFROM " + blob + "\nTEMPLATE {{ .Prompt }}\n"
	if got := blobPathFromModelfile(modelfile); got != blob {
		t.Fatalf("blob path = %q, want %q", got, blob)
	}
}

// The commented FROM line names a tag, not a file. Reading it would send the
// caller to open something that is not an artifact.
func TestCommentedFromLinesAreNotPaths(t *testing.T) {
	if got := blobPathFromModelfile("# FROM qwen3.6:27b\n"); got != "" {
		t.Fatalf("a commented FROM was read as a path: %q", got)
	}
}

// The modelfile is runtime-supplied text. Only an existing regular file is
// offered to the caller.
func TestOnlyExistingRegularFilesAreOffered(t *testing.T) {
	dir := t.TempDir()
	for _, test := range []struct{ name, modelfile string }{
		{"missing file", "FROM " + filepath.Join(dir, "absent") + "\n"},
		{"a directory", "FROM " + dir + "\n"},
		{"empty target", "FROM \n"},
		{"no from line", "TEMPLATE {{ .Prompt }}\n"},
		{"empty modelfile", ""},
	} {
		t.Run(test.name, func(t *testing.T) {
			if got := blobPathFromModelfile(test.modelfile); got != "" {
				t.Fatalf("offered %q for %s", got, test.name)
			}
		})
	}
}
